Finish Initial Retry Implementation
utopia-php/queue pull request #17
Opened 2023-12-29 11:22 UTC by PineappleIOnic

This PR implements Retry functionality into the Queue library, it will take all failed jobs in `{namespace}.failed.{queue}` and re-queue them while removing them from that list.

2023-12-29 11:29 UTC, eldadfux requested changes

2023-12-29 11:29 UTC, eldadfux commented on tests/Queue/e2e/AdapterTest.php
> +    public function testRetrySwoole(): void
Having a specific test here for Swoole is very messy. We need to follow same patterns we follow when testing adapters for other libraries. We would usually have one abstracted test that contain most of the tests and then a test class per adapter where in the constructor we just change the way we initialize the class. This way when adding an adapter we just need to add a single class with little code.

With current approach we open the door for a LOT of mess, and not too long before we can't control what is tested and what isn't.

2023-12-29 11:29 UTC, eldadfux commented on src/Queue/Client.php
> +        while (true) {
What happens in jobs that we just retried have failed? will we end up in an endless loop?

2023-12-29 11:29 UTC, eldadfux commented on src/Queue/Client.php
> +    public function retryFailedJobs(): void
This can just be `retry`. We also need the ability to control a specific queue, is this solved at the client level? are we using client per queue?

2023-12-29 11:31 UTC, PineappleIOnic commented on tests/Queue/e2e/AdapterTest.php
> +    public function testRetrySwoole(): void
Sorry, I was just trying to follow what was previously in the file. I'll refactor the tests accordingly

2023-12-29 11:32 UTC, PineappleIOnic commented on src/Queue/Client.php
> +        while (true) {
We don't re-queue the jobs in this while loop, instead I fetch all the failed jobs then queue them to prevent a infinite loop

2023-12-29 11:33 UTC, PineappleIOnic commented on src/Queue/Client.php
> +    public function retryFailedJobs(): void
Yeah, queue is set individually on clients

2023-12-29 14:30 UTC, eldadfux requested changes

2023-12-29 14:30 UTC, eldadfux commented on tests/Queue/e2e/Adapter/SwooleTest.php
> +    protected function testSwooleConcurrency(): void
Wouldn't we need the same test for other adapters? what if we need to switch in the future? We'll have no idea if we can trust the library.

2023-12-29 14:30 UTC, eldadfux commented on composer.json
> +        "psr-4": {"Tests\\E2E\\": "tests/Queue/e2e"}
The PHP convention here is to have the directories at the same name case as the classes.

2024-01-02 11:37 UTC, TorstenDittmann commented
How is the retry strategy applied in production?

As far as I can see here right now, is that we manually need to retry and it just works of all failed jobs. I am not sure if this is the most sane approach. Usually with all common libraries, the retry configuration is tied to a job. Meaning you enqueue a job while defining how its going to be retried.

I am not sure if blindly just working of failed jobs is good.

ref:
- https://docs.bullmq.io/guide/retrying-failing-jobs
- https://medium.com/insiderengineering/optimize-your-laravel-applications-performance-effective-strategies-for-implementing-job-retries-384da22e3a50

2024-01-02 11:40 UTC, PineappleIOnic commented
Right, I'll try and so some research and think of something better

2024-01-05 12:44 UTC, eldadfux reviewed
Where is the sum method I saw in the Appwrite PR? I can't seem to find it.

2024-01-05 12:44 UTC, eldadfux commented on src/Queue/Client.php
> +            if ($pid === false) {
What is this case? Let's add a comment

2024-01-05 12:44 UTC, eldadfux commented on src/Queue/Client.php
> +            if ($pid === false) {
Let's add a comment alongside each check.

2024-01-05 12:44 UTC, eldadfux commented on src/Queue/Client.php
> +            $pid = $this->connection->rightPop("{$this->namespace}.failed.{$this->queue}", 5);
What is the `5` here?

2024-01-05 12:48 UTC, PineappleIOnic commented on src/Queue/Client.php
> +            $pid = $this->connection->rightPop("{$this->namespace}.failed.{$this->queue}", 5);
I'm not entirely sure as I didn't write this method but from it's signature it appears to be a timeout, so if grabbing that rightPop data takes more than 5 seconds it'll quite and throw an exception.

2024-01-09 15:30 UTC, PineappleIOnic commented on src/Queue/Client.php
> +            if ($pid === false) {
I've added comments for all of the cases

2024-01-16 09:51 UTC, christyjacob4 commented on src/Queue/Client.php
> +    public function retry(int $limit = null): void
Can we add a doc block explaining what this function does and what the limit param means ?

2024-01-16 11:01 UTC, PineappleIOnic commented on src/Queue/Client.php
> +    public function retry(int $limit = null): void
Done

2024-01-17 11:06 UTC, christyjacob4 commented on src/Queue/Client.php
> +    public function retry(int $limit = null): void
Can we follow the proper syntax for doc blocks? 

`@param, @returns, @throws` etc?

2024-01-17 11:13 UTC, christyjacob4 commented on src/Queue/Connection/Redis.php
> +        return $results;
can you explain the changes here ?

2024-01-17 11:14 UTC, christyjacob4 commented on src/Queue/Connection/Redis.php
> -        return array_map(fn (array $job) => new Message($job), $results);
also previously we returned an array of Message objects. and now its just an array ?

2024-01-17 12:34 UTC, christyjacob4 commented on tests/Queue/E2E/Adapter/Base.php
> +        // Meaning this test has 5 failed jobs due to the previous tests.
```suggestion
```

2024-01-17 19:00 UTC, christyjacob4 approved these changes

2024-01-17 19:00 UTC, merged